const Commands = require(`../../../../__Global/Structures/Commands`);
const asciify = require(`asciify`);

class Command extends Commands {
	constructor(client) {
		super(client, {
			enabled: true,
			show: true,
			cooldown: false,
			cooldownAmount: 1,
			cooldownTime: 3,
			limit: false,
			limitAmount: 3,
			limitTime: 86400,
			description: `Converts the text to an ascii`,
			usage: `[Font] [Text]`,
			aliases: []
		});
	}

	run(client, message, args) {
		if (args.length < 1) return client.missingArgs(message, this);

		const fonts = [
			`3-d`,
			`3x5`,
			`5lineoblique`,
			`acrobatic`,
			`alligator`,
			`alligator2`,
			`alphabet`,
			`avatar`,
			`banner`,
			`banner3-D`,
			`banner3`,
			`banner4`,
			`barbwire`,
			`basic`,
			`bell`,
			`big`,
			`bigchief`,
			`binary`,
			`block`,
			`bubble`,
			`bulbhead`,
			`calgphy2`,
			`caligraphy`,
			`catwalk`,
			`chunky`,
			`coinstak`,
			`colossal`,
			`computer`,
			`contessa`,
			`contrast`,
			`cosmic`,
			`cosmike`,
			`cricket`,
			`cursive`,
			`cyberlarge`,
			`cybermedium`,
			`cybersmall`,
			`diamond`,
			`digital`,
			`doh`,
			`doom`,
			`dotmatrix`,
			`drpepper`,
			`eftichess`,
			`eftifont`,
			`eftipiti`,
			`eftirobot`,
			`eftitalic`,
			`eftiwall`,
			`eftiwater`,
			`epic`,
			`fender`,
			`fourtops`,
			`fuzzy`,
			`goofy`,
			`gothic`,
			`graffiti`,
			`hollywood`,
			`invita`,
			`isometric1`,
			`isometric2`,
			`isometric3`,
			`isometric4`,
			`italic`,
			`ivrit`,
			`jazmine`,
			`jerusalem`,
			`katakana`,
			`kban`,
			`larry3d`,
			`lcd`,
			`lean`,
			`letters`,
			`linux`,
			`lockergnome`,
			`madrid`,
			`marquee`,
			`maxfour`,
			`mike`,
			`mini`,
			`mirror`,
			`mnemonic`,
			`morse`,
			`moscow`,
			`nancyj-fancy`,
			`nancyj-underlined`,
			`nancyj`,
			`nipples`,
			`ntgreek`,
			`o8`,
			`ogre`,
			`pawp`,
			`peaks`,
			`pebbles`,
			`pepper`,
			`poison`,
			`puffy`,
			`pyramid`,
			`relief`,
			`relief2`,
			`rev`,
			`roman`,
			`rot13`,
			`rounded`,
			`rowancap`,
			`rozzo`,
			`runic`,
			`runyc`,
			`sblood`,
			`script`,
			`serifcap`,
			`shadow`,
			`short`,
			`slant`,
			`slide`,
			`slscript`,
			`small`,
			`smisome1`,
			`smkeyboard`,
			`smscript`,
			`smshadow`,
			`smslant`,
			`smtengwar`,
			`speed`,
			`stampatello`,
			`standard`,
			`starwars`,
			`stellar`,
			`stop`,
			`straight`,
			`tanja`,
			`tengwar`,
			`term`,
			`thick`,
			`thin`,
			`threepoint`,
			`ticks`,
			`ticksslant`,
			`tinker-toy`,
			`tombstone`,
			`trek`,
			`tsalagi`,
			`twopoint`,
			`univers`,
			`usaflag`,
			`wavy`,
			`weird`
		];

		const font = args.shift();

		if (!fonts.includes(font)) return message.channel.send(`\`${font}\` is not in the list, <https://pastebin.com/FDSANJ38>`);

		asciify(args.join(` `), font, (error, response) => {
			if (error) return message.channel.send(error, { code: `` });
			message.channel.send(response, { code: `` });
		});
		return true;
	}
}

module.exports = Command;
